### ISSUE TITLE
Route 1 stops on website

### ISSUE THREAD

**Issue by meredithshores** [GOLewis-McChord/go_src#1]
Product: website
Source: unknown
Goal: show all route 1 stops on website
Error: unknown
Description: Stops 309-315 for Route 1 and stop 780 are not appearing on the website map. More may be missing but we aren't sure. They appear in the stop.kml file except for 780, however this kml folder(it's src/static/kml) isn't the "web" folder so I don't know how it gets uploaded to the web. They only file I can find for stops in the web folder is landmark.csv and it does include all the stops.

**Comment by mlockwood** [comment]
Neil made a new commit on 20161005 to:
https://github.com/GOLewis-McChord/go_src/tree/master/static/kml

Reading that file the stops are not there. Simply add them to the file and then recommit.

I am closing this issue but if you have errors in that process open a new report.
