### ISSUE TITLE
missing stop locations

### ISSUE THREAD

**Issue by nquisen** [GOLewis-McChord/go_src#3]
Product: GIT
Source: go/src/static/kml/stops.kml
Goal: Add missing stop locations
Error: Stop locations missing from Go Lewis McChord map
Description: I got the message relayed through Meredith.  I haven't changed the stop locations and all the "missing" stop locations are in my kml file on our network so I don't know why they wouldn't show up on GitHub.  I tried doing a fresh pull and then push from the src folder.  Pull was fine but when I push I get a rejected error (photo attached)
![git_rejected](https://cloud.githubusercontent.com/assets/22526468/20400218/ad079b0e-aca8-11e6-85b1-3262e0d18142.JPG)

nquisen@co.pierce.wa.us

**Comment by mlockwood** [comment]
Can you run "git status"? You make have new items to commit.

If you look online you should be able to follow instructions for debugging issues like these. I am not sure the entire process and work flow that got you to this point.

**Comment by nquisen** [comment]
I don’t think we ever went through git commit commands.

If I recall correctly I did a git pull, ran master.py, and did a git push.

When I run git status I get the following message (pic below).  It looks like it wants me to commit the changes to the scripts and stops.kml.  As well as I can remember I didn’t change the stops.  I only created a new kml file to remove the levito piece of that route.
[cid:image002.png@01D241A5.2555B970]

I tried doing a “git add stops.kml” and then directly trying a git commit – m “stops” but both ended in the error result below.  I’ll ask Meredith if she has it open when she gets back.
[cid:image001.png@01D241A5.0CE5C600]

**Comment by mlockwood** [comment]
I am sorry I think you may have responded via email and the pictures did not appear. What I meant is that this is a common git issue that you could debug via Google search of the issue. In this case an error to push to a remote repository (GitHub).

**Comment by nquisen** [comment]
I don’t think we ever went through git commit commands.  

If I recall correctly I did a git pull, ran master.py, and did a git push.  

When I run git status I get the following message (pic below).  It looks like it wants me to commit the changes to the scripts and stops.kml.  As well as I can remember I didn’t change the stops.  I only created a new kml file to remove the levito piece of that route.
 

I tried doing a “git add stops.kml” and then directly trying a git commit – m “stops” but both ended in the error result below.  I’ll ask Meredith if she has it open when she gets back.
 

![gitstatus](https://cloud.githubusercontent.com/assets/22526468/20448700/25a324ce-ad9a-11e6-9656-118b30ab9340.png)
![gitcommit](https://cloud.githubusercontent.com/assets/22526468/20448710/345faabe-ad9a-11e6-8826-1bf227ba1782.png)

**Comment by nquisen** [comment]
I did respond to the last one through email since the signature of the email says I can reply directly.  I guess not if there are pictures

**Comment by mlockwood** [comment]
I think we did? Either way you did it once because you were able to commit before. But no worries I think we can solve this. Run: `git commit -m "Changes to ridership and stops."` Then attempt the push. Does this work?

**Comment by nquisen** [comment]
Similar error as last time I tried it.  Odd that it's not identical.  I asked Meredith and she said she doesn't have anything open.
![gitcommit2](https://cloud.githubusercontent.com/assets/22526468/20448903/2629657e-ad9b-11e6-9f41-0bb373c49837.JPG)

**Comment by mlockwood** [comment]
Someone else (probably Meredith) started and added contents and didn't commit them or a commit didn't complete so there is a lock. I would research on Google what to do. Although I suspect that you could delete the index.lock file.

**Comment by nquisen** [comment]
OK, so I deleted the lock file.  No difference but I found a document Meredith had written that mentions git commit.  I tried another "git add ."   and it worked.  However it still fails when I try to push it.  
![gitcommit3](https://cloud.githubusercontent.com/assets/22526468/20449151/8e0b7e9c-ad9c-11e6-99f8-1b1cef04190f.JPG)

ummm, I followed the hint and ran another git pull and it gave me a weird message about merging branches and leaving a message before proceeding.  Should I type something.  The screen is odd now.  Had to move my cursor a lot just to get it to a place where I could type.

**Comment by nquisen** [comment]
OK, I didn't want to risk it so I just closed the window.  When I typed and hit enter it just went down to the next line anyway, seemed screwed up. 
Opened GitBash again, did a push and it seems to have worked.  GoLewisMcChord website appears to have the missing stops now.  I think that's what the original problem was??? Trying to get multiple things done before the end of the week.

Thanks

**Comment by mlockwood** [comment]
Glad you were able to get a resolution that worked!
