### ISSUE TITLE
GTFS calendar

### ISSUE THREAD

**Issue by nquisen** [GOLewis-McChord/go_src#5]
Product: GTFS
Source: script
Goal: new route schedule for GTFS
Error: Route schedule expired October 31st but I don't know how to change the date.  There are also shp errors
Description.  I just ran master.py so everything should be updated but I never figured out how to change the date.  We ran into this a month ago but you were dealing with the database so I didn't want to bother you.  I was hoping the shape errors would fix themselves once the database was fixed. I attached the validation report.  Used zip because html isn't supported through this.
[validation-results.zip](https://github.com/GOLewis-McChord/go_src/files/625928/validation-results.zip)

**Comment by mlockwood** [comment]
This is a problem with the route planning not anything in the code. The only part the code controls is which date to publish for. As a default it is set to whatever the current day is. So if something is published with an October date then that is an issue with what is online. Although last I checked the dates were fixed online so this would mean the script is not pulling fresh data?

**Comment by nquisen** [comment]
It appears that it's not pulling fresh data.  When I run the feedvalidator it gives me an expiration date error saying Oct 31st is the last date in calendar.txt.  When I look at the calendar.txt file date stamp it's 9/29 which I'm assuming you ran just before you left.  I just tried running route.py outside of master.py and it ran fine but same validation results.

**Comment by mlockwood** [comment]
If you checked calendar.txt that tells me that you are not outputting, not that you are not pulling new data. I store all data in JSON files. So if you look into the data/route directory you will see whether or not you are pulling the latest data. Somehow something is off if you are not outputting reports. Are you checking the reports folder or the src folder for GTFS? You might be operating just fine but looking in src when you should go to reports. Src had a copy only to store the validation files.

**Comment by nquisen** [comment]
Checked data/route all json files except for direction and transfer have todays date, so it's pulling the data though the date_range is odd for the last range.  end 2017-10-02   start 2016-08-29.  I wish it was as simple as looking in the wrong folder.  Have been looking in the reports folder.
